### ISSUE TITLE
requires mapblox-gl which doesn't have a standard license?

### ISSUE THREAD

**Issue by gardnerjr** [Azure/react-azure-maps#108]
We noticed that this package requires mapblox-gl: https://www.npmjs.com/package/mapbox-gl
which doesn't have any standard license, so inside Microsoft, it gets flagged in Component Governance as "missing legal info"

Is `mapblox-gl` *required* for this wrapper?  or could it be made an optional component?

**Comment by rbrundritt** [comment]
Version 1 of the Azure Maps Web SDK uses and older version of the Mapbox SDK. Version 2 of the Azure Maps Web SDK (which this library is based on) uses MapLibre: https://maplibre.org/

So with that in mind, mapbox-gl likely isn't needed for this library. I suspect it might have been added when this library was initially created and just ignored since. Strangely it looks like the only other reference to Mapbox in this project is loading its CSS here: https://github.com/Azure/react-azure-maps/blob/907b2ddf44120a9d55c4ca2c53fb00dc4bc64004/src/components/AzureMap/AzureMap.tsx which is more likely to create an issue in the future.

**Comment by yulinscottkang** [comment]
react-azure-maps@next (1.0.0) has removed the CSS import. Please refer to [MIGRATION.md](https://github.com/Azure/react-azure-maps/blob/version-1.0/MIGRATION.md) for more details.
